name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build-bookmark-api:
    name: Build bookmark-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookmark-api
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw verify

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bookmark-api:latest .

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and publish Docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/bookmark-api

      - if: ${{ github.ref != 'refs/heads/main' }}
        name: Branch is not main
        run: echo "This branch is not main"
